# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Language.create(abbreviation: 'en', name: 'English')
Language.create(abbreviation: 'fr', name: 'French')
Language.create(abbreviation: 'es', name: 'Spanish')
Language.create(abbreviation: 'ko', name: 'Korean')
Language.create(abbreviation: 'de', name: 'German')
Language.create(abbreviation: 'ru', name: 'Russian')
Language.create(abbreviation: 'pt', name: 'Portuguese')
Language.create(abbreviation: 'th', name: 'Thai')
Language.create(abbreviation: 'zh', name: 'Chinese')
Language.create(abbreviation: 'tr', name: 'Turkish')
Language.create(abbreviation: 'ja', name: 'Japanese')
Language.create(abbreviation: 'it', name: 'Italian')
Language.create(abbreviation: 'pl', name: 'Polish')
Language.create(abbreviation: 'it', name: 'Italian')
Language.create(abbreviation: 'am', name: 'Amharic')
Language.create(abbreviation: 'ar', name: 'Arabic')
Language.create(abbreviation: 'eu', name: 'Basque')
Language.create(abbreviation: 'eu', name: 'Basque')

Game.create(name: "Miscellaneous", category: "Miscaellaneous", twitch_game_id: "0", box_art: "https://static-cdn.jtvnw.net/ttv-boxart/Littlewood-272x380.jpg")


Language.create(name: 'Bengali	', abbreviation: 'bn')
Language.create(name: 'Bulgarian	', abbreviation: 'bg')
Language.create(name: 'Catalan	', abbreviation: 'ca')
Language.create(name: 'Cherokee	', abbreviation: 'chr')
Language.create(name: 'Croatian	', abbreviation: 'hr')
Language.create(name: 'Czech	', abbreviation: 'cs')
Language.create(name: 'Danish	', abbreviation: 'da')
Language.create(name: 'Dutch	', abbreviation: 'nl')
Language.create(name: 'Estonian	', abbreviation: 'et')
Language.create(name: 'Filipino	', abbreviation: 'fil')
Language.create(name: 'Finnish	', abbreviation: 'fi')
Language.create(name: 'Greek	', abbreviation: 'el')
Language.create(name: 'Gujarati	', abbreviation: 'gu')
Language.create(name: 'Hebrew	', abbreviation: 'iw')
Language.create(name: 'Hindi	', abbreviation: 'hi')
Language.create(name: 'Hungarian	', abbreviation: 'hu')
Language.create(name: 'Icelandic	', abbreviation: 'is')
Language.create(name: 'Indonesian	', abbreviation: 'id')
Language.create(name: 'Kannada	', abbreviation: 'kn')
Language.create(name: 'Korean	', abbreviation: 'ko')
Language.create(name: 'Latvian	', abbreviation: 'lv')
Language.create(name: 'Lithuanian	', abbreviation: 'lt')
Language.create(name: 'Malay	', abbreviation: 'ms')
Language.create(name: 'Malayalam	', abbreviation: 'ml')
Language.create(name: 'Marathi	', abbreviation: 'mr')
Language.create(name: 'Norwegian	', abbreviation: 'no')
Language.create(name: 'Romanian	', abbreviation: 'ro')
Language.create(name: 'Serbian	', abbreviation: 'sr')
Language.create(name: 'Slovak	', abbreviation: 'sk')
Language.create(name: 'Slovenian	', abbreviation: 'sl')
Language.create(name: 'Spanish	', abbreviation: 'es')
Language.create(name: 'Swahili	', abbreviation: 'sw')
Language.create(name: 'Swedish	', abbreviation: 'sv')
Language.create(name: 'Tamil	', abbreviation: 'ta')
Language.create(name: 'Telugu	', abbreviation: 'te')
Language.create(name: 'Turkish	', abbreviation: 'tr')
Language.create(name: 'Urdu	', abbreviation: 'ur')
Language.create(name: 'Ukrainian	', abbreviation: 'uk')
Language.create(name: 'Vietnamese	', abbreviation: 'vi')
Language.create(name: 'Welsh	', abbreviation: 'cy')
Language.create(name: 'NA', abbreviation: 'none')
